"""add_payment_confirmation_and_quarter_to_qpd_calculations

Revision ID: 180e8e96641d
Revises: ddd1042210c3
Create Date: 2026-09-25 09:39:02.441800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '180e8e96641d'
down_revision: Union[str, None] = 'ddd1042210c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qpd_calculations', sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qpd_calculations', 'payment_confirmed_at')
    # ### end Alembic commands ###
