"""add qpd quarter and actual paid fields

Revision ID: afa72ebeef86
Revises: b5ee90ca9f62
Create Date: 2026-08-18 09:42:57.850339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa72ebeef86'
down_revision: Union[str, None] = 'b5ee90ca9f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qpd_calculations', sa.Column('quarter', sa.Integer(), server_default='1', nullable=False))
    op.add_column('qpd_calculations', sa.Column('actual_usd_paid', sa.Float(), nullable=True))
    op.add_column('qpd_calculations', sa.Column('actual_zig_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qpd_calculations', 'actual_zig_paid')
    op.drop_column('qpd_calculations', 'actual_usd_paid')
    op.drop_column('qpd_calculations', 'quarter')
    # ### end Alembic commands ###
