"""add monthly_income_entries table

Revision ID: d2d04b923a1a
Revises: 50ca60f2e43f
Create Date: 2026-09-22 10:50:40.595025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d04b923a1a'
down_revision: Union[str, None] = '50ca60f2e43f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_income_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('usd_amount', sa.Float(), nullable=False),
    sa.Column('zig_amount', sa.Float(), nullable=False),
    sa.Column('is_estimate', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'tax_year', 'month', name='uq_monthly_income_period')
    )
    op.create_index(op.f('ix_monthly_income_entries_business_id'), 'monthly_income_entries', ['business_id'], unique=False)
    op.create_index(op.f('ix_monthly_income_entries_tax_year'), 'monthly_income_entries', ['tax_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthly_income_entries_tax_year'), table_name='monthly_income_entries')
    op.drop_index(op.f('ix_monthly_income_entries_business_id'), table_name='monthly_income_entries')
    op.drop_table('monthly_income_entries')
    # ### end Alembic commands ###
