"""add_capital_assets_business_id_index

Revision ID: ddd1042210c3
Revises: d2d04b923a1a
Create Date: 2026-09-24 09:28:19.998226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddd1042210c3'
down_revision: Union[str, None] = 'd2d04b923a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_capital_assets_business_id'), 'capital_assets', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capital_assets_business_id'), table_name='capital_assets')
    # ### end Alembic commands ###
